[build-system]
requires = ["setuptools", "wheel", "babel>2.8"]
build-backend = "setuptools.build_meta"


[tool.ruff]
select = ["ALL"]
ignore = ["ANN101", "ANN102", "D203", "D211", "D212", "D213", "N802"]
